# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-17 23:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternativa_descricao', models.CharField(max_length=50)),
                ('alternativa_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField()),
                ('data', models.DateField()),
                ('autor', models.CharField(max_length=20)),
                ('disciplina', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('alternativa_correta', models.CharField(max_length=1)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provas.Prova')),
            ],
        ),
        migrations.AddField(
            model_name='alternativa',
            name='questao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provas.Questao'),
        ),
    ]
