# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-19 04:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provas', '0002_auto_20161019_0157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questao',
            old_name='disciplina',
            new_name='prova',
        ),
    ]
