# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-20 00:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provas', '0006_auto_20161019_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternativa_descricao', models.CharField(max_length=50)),
                ('alternativa_id', models.IntegerField()),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provas.Questao')),
            ],
        ),
    ]
