# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-21 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provas', '0007_alternativa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternativa',
            name='questao',
        ),
        migrations.RemoveField(
            model_name='questao',
            name='descricao',
        ),
        migrations.AddField(
            model_name='questao',
            name='alternativa_01',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='questao',
            name='alternativa_02',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='questao',
            name='alternativa_03',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='questao',
            name='alternativa_04',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='questao',
            name='alternativa_05',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='questao',
            name='enunciado',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Alternativa',
        ),
    ]
