# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-21 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provas', '0008_auto_20161021_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prova',
            name='nivel',
            field=models.IntegerField(choices=[(1, 'Fácil'), (2, 'Normal'), (3, 'Difícil')], default=2),
        ),
    ]
