# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-21 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provas', '0009_auto_20161021_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='alternativa_correta',
            field=models.IntegerField(choices=[(1, 'a'), (2, 'b'), (3, 'c'), (4, 'd'), (5, 'e')]),
        ),
    ]
