# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-21 22:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provas', '0010_auto_20161021_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questao',
            old_name='alternativa_01',
            new_name='alternativa_a',
        ),
        migrations.RenameField(
            model_name='questao',
            old_name='alternativa_02',
            new_name='alternativa_b',
        ),
        migrations.RenameField(
            model_name='questao',
            old_name='alternativa_03',
            new_name='alternativa_c',
        ),
        migrations.RenameField(
            model_name='questao',
            old_name='alternativa_04',
            new_name='alternativa_d',
        ),
        migrations.RenameField(
            model_name='questao',
            old_name='alternativa_05',
            new_name='alternativa_e',
        ),
    ]
